# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci -- --coverage
      - run: npm test
      - name: Codecov
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@6004246f47ab62d32be025ce173b241cd84ac58e
        uses: codecov/codecov-action@v1.0.13
        with:
          # User defined upload name. Visible in Codecov UI
          name: node-wsl
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: ${{ secrets.CODECOV_TOKEN }}
          # Path to coverage file to upload
          #file: # optional
          # Comma-separated list of files to upload
          #files: # optional
          # Directory to search for coverage reports.
          directory: ./coverage
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          #flags: # optional
          # Write upload file to path before uploading
          path_to_write_report: ./coverage/codecov_report.gz
          # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
          #env_vars: # optional
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: true
